# Generated by Django 3.1.7 on 2021-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.URLField(default='https://i.pinimg.com/474x/9b/47/a0/9b47a023caf29f113237d61170f34ad9.jpg'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Address',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
